In [1]:
import pandas as pd

In [2]:
dfAvo = pd.read_csv('./avocado.csv')
dfAvo

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
18246,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
18247,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
18248,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

In [3]:
# average prices across all to get average price at a particular date
avgPrices = dfAvo.groupby(dfAvo['Date'])

dfAvgP = pd.DataFrame(avgPrices['AveragePrice'].mean())
dfAvgP

            AveragePrice
Date
2015-01-04      1.301296
2015-01-11      1.370648
2015-01-18      1.391111
2015-01-25      1.397130
2015-02-01      1.247037
...                  ...
2018-02-25      1.359630
2018-03-04      1.350185
2018-03-11      1.335093
2018-03-18      1.313704
2018-03-25      1.346852

[169 rows x 1 columns]

In [4]:
dfAvgP.to_csv('./avoCleaned.csv')

In [5]:
dfEcon = pd.read_csv('./macroeconomics.csv')
dfEcon

,date,Gross Domestic Product,Gross National Product,Gross domestic product per capita,Sticky Price Consumer Price Index less Food and Energy,Producer Price Index by Commodity: All Commodities,Unemployment Rate,Labor Force Participation Rate,Personal Consumption Expenditures,Net domestic investment: Private: Domestic business,...,"Rest of the World; Foreign Direct Investment in U.S.; Asset (Current Cost), Transactions (Growth)",Equity Market Volatility Tracker: Exchange Rates (Growth),Producer Price Index by Commodity: Metals and Metal Products: Gold Ores (Growth),15-Year Fixed Rate Mortgage Average in the United States (Growth),Disposable Personal Income (Growth),CBOE Volatility Index: VIX (Growth),ICE BofA US High Yield Index Effective Yield (Growth),Employment Cost Index: Total compensation: All Civilian (Growth),Federal Debt: Total Public Debt as Percent of Gross Domestic Product (Growth),Personal Saving (Growth)
0,1/01/2001,10470.231,10510.297,36845,2.950054,137.767,4.2,67.2,6995.3,414.895,...,-39.19648,36.70127,-1.04966,-9.66994,1.56330,-1.11550,-5.83002,0.00000,1.63375,11.72283
1,4/1/2001,10599.000,10647.427,37211,3.132302,136.233,4.4,66.8,7042.2,384.743,...,0.60637,-53.42862,-0.61200,1.07401,0.21149,-7.00696,0.37295,0.94451,-2.01778,-7.80799
2,7/1/2001,10598.020,10623.039,37110,3.293858,133.367,4.8,66.7,7070.3,336.012,...,-76.28098,60.10720,4.02299,-2.29845,2.23298,6.08820,0.45458,1.05263,1.41765,40.18063
3,10/1/2001,10660.465,10748.408,37234,3.560389,129.400,5.5,66.7,7187.3,229.850,...,148.78964,5.45581,0.94712,-3.90117,-1.62106,9.96701,0.86613,0.92593,1.74192,-46.70304
4,1/1/2002,10783.500,10833.143,37582,3.529122,128.900,5.7,66.6,7217.7,269.353,...,-29.60255,84.06751,4.80844,3.33374,2.55276,-23.46531,-6.07268,0.80275,-0.09983,64.94388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,10/1/2021,24349.121,24530.587,73168,3.244694,241.697,4.2,61.9,16518.0,725.950,...,-7.41227,0.00000,-0.37385,7.69231,0.24046,5.40162,8.10724,1.09215,0.76256,-19.89096
84,1/1/2022,24740.480,24929.184,74301,4.284717,253.042,3.8,62.3,16874.8,783.017,...,-34.43537,0.00000,0.00000,30.19737,-0.98986,31.63527,21.75209,1.35044,1.02254,-41.29833
85,4/1/2022,25248.476,25456.409,75748,5.043241,272.937,3.6,62.2,17261.4,669.201,...,10.18161,0.00000,0.00000,46.18494,1.18537,7.98306,35.23000,1.33245,-1.47171,-24.68680
86,7/1/2022,25723.941,25885.432,77064,6.003276,269.906,3.6,62.2,17542.7,612.164,...,28.49093,85.90391,0.00000,9.66125,1.86607,-9.51043,12.67451,1.18343,-0.69136,2.93786
87,10/1/2022,26137.992,26289.489,78191,6.484403,262.038,3.6,62.2,17749.9,707.738,...,-34.20205,-22.78823,0.00000,22.09614,1.55964,0.84674,7.86283,1.10461,-0.02245,6.48042

In [6]:
dfEcon['date'] = pd.to_datetime(dfEcon['date'])
dfEcon['year'] = [date.year for date in dfEcon['date']]
dfEcon = dfEcon.where(dfEcon['year'] >= 2015).dropna()
dfEcon = dfEcon.where(dfEcon['year'] <= 2018).dropna()
dfEcon

,date,Gross Domestic Product,Gross National Product,Gross domestic product per capita,Sticky Price Consumer Price Index less Food and Energy,Producer Price Index by Commodity: All Commodities,Unemployment Rate,Labor Force Participation Rate,Personal Consumption Expenditures,Net domestic investment: Private: Domestic business,...,Equity Market Volatility Tracker: Exchange Rates (Growth),Producer Price Index by Commodity: Metals and Metal Products: Gold Ores (Growth),15-Year Fixed Rate Mortgage Average in the United States (Growth),Disposable Personal Income (Growth),CBOE Volatility Index: VIX (Growth),ICE BofA US High Yield Index Effective Yield (Growth),Employment Cost Index: Total compensation: All Civilian (Growth),Federal Debt: Total Public Debt as Percent of Gross Domestic Product (Growth),Personal Saving (Growth),year
56,2015-01-01,17991.348,18214.218,56018.0,1.988929,191.533,5.5,62.7,12083.9,673.329,...,155.00868,0.89735,-5.14926,0.91013,3.06371,0.56806,0.65147,-0.71348,8.71881,2015.0
57,2015-04-01,18193.707,18405.862,56547.0,2.081581,193.033,5.4,62.8,12224.7,649.385,...,-68.70157,-2.15835,1.50525,0.76338,-17.05184,-2.77764,0.16181,-1.11256,-4.39124,2015.0
58,2015-07-01,18306.960,18520.403,56779.0,2.200373,191.633,5.1,62.5,12347.7,624.540,...,1216.73836,-5.58696,3.09590,0.82281,40.51648,15.73235,0.64620,-0.62619,-1.72559,2015.0
59,2015-10-01,18332.079,18565.145,56736.0,2.398386,185.567,5.0,62.6,12397.5,562.637,...,-86.72288,-0.43443,-0.86321,0.52041,-11.77751,12.18652,0.56180,4.10803,1.68988,2015.0
60,2016-01-01,18425.306,18640.558,56923.0,2.514270,182.000,4.9,62.8,12495.1,499.299,...,231.03060,3.46698,-3.24192,0.81067,20.27177,12.38093,0.55866,1.29628,1.86628,2016.0
61,2016-04-01,18611.617,18827.942,57396.0,2.559352,185.367,4.9,62.8,12637.4,473.144,...,-62.62761,7.56781,-5.67574,0.46234,-23.48061,-15.49078,0.55556,-0.40160,-7.31560,2016.0
62,2016-07-01,18775.459,18995.777,57784.0,2.643587,187.067,4.9,62.9,12759.1,458.681,...,-40.97228,6.62217,-3.53481,0.86020,-15.57822,-13.86818,0.55249,0.10860,-0.86631,2016.0
63,2016-10-01,18968.041,19243.922,58263.0,2.543421,187.067,4.8,62.7,12881.5,512.798,...,-25.90110,-7.08536,12.72727,1.00637,6.52891,-3.82259,0.54945,1.02465,1.35936,2016.0
64,2017-01-01,19148.194,19420.467,58727.0,2.596455,191.267,4.6,62.9,13049.4,465.199,...,22.41788,-2.68449,9.52854,1.57493,-17.06633,-6.85295,0.62451,-1.58749,5.75456,2017.0
65,2017-04-01,19304.506,19568.667,59116.0,2.182204,193.133,4.4,62.9,13134.0,503.699,...,12.05493,4.18727,-4.64431,1.24187,-2.27153,-3.99700,0.62064,-0.81904,8.11685,2017.0
66,2017-07-01,19561.896,19870.351,59797.0,2.114433,194.033,4.3,63.0,13260.3,547.469,...,-43.20502,1.74051,-2.20955,0.93695,-4.21888,-0.83582,0.69391,0.67509,0.45183,2017.0
67,2017-10-01,19894.750,20221.660,60712.0,2.144441,195.700,4.2,62.7,13490.7,571.187,...,31.86376,0.31104,3.93586,1.04463,-5.81444,1.14137,0.61256,-0.46931,-7.80138,2017.0
68,2018-01-01,20155.486,20467.925,61433.0,2.222466,198.833,4.0,62.9,13677.4,600.649,...,-71.10802,3.28682,13.65124,1.73281,68.36303,6.38048,0.76104,1.58142,6.33239,2018.0
69,2018-04-01,20470.197,20772.518,62309.0,2.530544,202.567,3.9,62.9,13850.8,603.892,...,96.28392,-0.25018,7.34266,1.37960,-11.62364,2.98832,0.67976,-1.04520,2.47934,2018.0
70,2018-07-01,20687.278,20958.320,62872.0,2.471482,203.767,3.8,62.8,13988.8,679.700,...,338.17986,-8.04575,0.47902,1.43011,-16.17392,0.81538,0.75019,0.44921,6.14326,2018.0
71,2018-10-01,20819.269,21094.695,63180.0,2.452051,202.633,3.8,62.9,14102.9,671.171,...,-100.00000,0.53458,4.42410,1.47146,63.75466,11.28292,0.74460,1.48133,9.48603,2018.0

In [7]:
econ_cleaned = pd.DataFrame()
econ_cleaned['date'] = dfEcon['date']
econ_cleaned['GDP'] = dfEcon['Gross Domestic Product']
econ_cleaned['GNP'] = dfEcon['Gross National Product']
econ_cleaned['Unemployment Rate'] = dfEcon['Unemployment Rate']
econ_cleaned['Labor Force Participation Rate'] = dfEcon['Labor Force Participation Rate']
econ_cleaned['Personal Consumption Expenditures'] = dfEcon['Personal Consumption Expenditures']
econ_cleaned['Trade Balance'] = dfEcon['Trade Balance: Goods and Services, Balance of Payments Basis']
econ_cleaned['Real Export'] = dfEcon['Real Exports of Goods and Services']
econ_cleaned['Personal Income'] = dfEcon['Disposable Personal Income']
econ_cleaned['Personal Saving'] = dfEcon['Personal Saving']
econ_cleaned

,date,GDP,GNP,Unemployment Rate,Labor Force Participation Rate,Personal Consumption Expenditures,Trade Balance,Real Export,Personal Income,Personal Saving
56,2015-01-01,17991.348,18214.218,5.5,62.7,12083.9,-40500.0,-3.2,13593.1,1074.9
57,2015-04-01,18193.707,18405.862,5.4,62.8,12224.7,-40254.0,1.1,13696.9,1027.7
58,2015-07-01,18306.960,18520.403,5.1,62.5,12347.7,-42062.0,-3.3,13809.6,1009.9
59,2015-10-01,18332.079,18565.145,5.0,62.6,12397.5,-40776.0,-0.6,13881.5,1027.0
60,2016-01-01,18425.306,18640.558,4.9,62.8,12495.1,-40050.0,-1.2,13994.0,1046.2
61,2016-04-01,18611.617,18827.942,4.9,62.8,12637.4,-39600.0,3.1,14058.7,969.6
62,2016-07-01,18775.459,18995.777,4.9,62.9,12759.1,-39027.0,6.4,14179.6,961.2
63,2016-10-01,18968.041,19243.922,4.8,62.7,12881.5,-41142.0,-2.8,14322.3,974.3
64,2017-01-01,19148.194,19420.467,4.6,62.9,13049.4,-41488.0,10.8,14547.9,1030.4
65,2017-04-01,19304.506,19568.667,4.4,62.9,13134.0,-43597.0,1.3,14728.6,1114.0
66,2017-07-01,19561.896,19870.351,4.3,63.0,13260.3,-42279.0,2.4,14866.6,1119.0
67,2017-10-01,19894.750,20221.660,4.2,62.7,13490.7,-44949.0,10.8,15021.9,1031.7
68,2018-01-01,20155.486,20467.925,4.0,62.9,13677.4,-46458.0,2.6,15282.2,1097.1
69,2018-04-01,20470.197,20772.518,3.9,62.9,13850.8,-44120.0,2.2,15493.0,1124.3
70,2018-07-01,20687.278,20958.320,3.8,62.8,13988.8,-49931.0,-5.2,15714.6,1193.3
71,2018-10-01,20819.269,21094.695,3.8,62.9,14102.9,-52355.0,1.2,15945.8,1306.5

In [8]:
# Mapping each row to calendar quarter
econ_cleaned['date'] = pd.to_datetime(econ_cleaned['date'])
quarter = []
year = []
for date in econ_cleaned['date']:
    year.append(date.year)
    if date.month == 4:
        quarter.append('Q1')
    elif date.month == 7:
        quarter.append('Q2')
    elif date.month == 10:
        quarter.append('Q3')
    else:
        quarter.append('Q4')
econ_cleaned['quarter'] = quarter
econ_cleaned['year'] = year
econ_cleaned = econ_cleaned.drop('date', axis=1)
econ_cleaned

,GDP,GNP,Unemployment Rate,Labor Force Participation Rate,Personal Consumption Expenditures,Trade Balance,Real Export,Personal Income,Personal Saving,quarter,year
56,17991.348,18214.218,5.5,62.7,12083.9,-40500.0,-3.2,13593.1,1074.9,Q4,2015
57,18193.707,18405.862,5.4,62.8,12224.7,-40254.0,1.1,13696.9,1027.7,Q1,2015
58,18306.960,18520.403,5.1,62.5,12347.7,-42062.0,-3.3,13809.6,1009.9,Q2,2015
59,18332.079,18565.145,5.0,62.6,12397.5,-40776.0,-0.6,13881.5,1027.0,Q3,2015
60,18425.306,18640.558,4.9,62.8,12495.1,-40050.0,-1.2,13994.0,1046.2,Q4,2016
61,18611.617,18827.942,4.9,62.8,12637.4,-39600.0,3.1,14058.7,969.6,Q1,2016
62,18775.459,18995.777,4.9,62.9,12759.1,-39027.0,6.4,14179.6,961.2,Q2,2016
63,18968.041,19243.922,4.8,62.7,12881.5,-41142.0,-2.8,14322.3,974.3,Q3,2016
64,19148.194,19420.467,4.6,62.9,13049.4,-41488.0,10.8,14547.9,1030.4,Q4,2017
65,19304.506,19568.667,4.4,62.9,13134.0,-43597.0,1.3,14728.6,1114.0,Q1,2017
66,19561.896,19870.351,4.3,63.0,13260.3,-42279.0,2.4,14866.6,1119.0,Q2,2017
67,19894.750,20221.660,4.2,62.7,13490.7,-44949.0,10.8,15021.9,1031.7,Q3,2017
68,20155.486,20467.925,4.0,62.9,13677.4,-46458.0,2.6,15282.2,1097.1,Q4,2018
69,20470.197,20772.518,3.9,62.9,13850.8,-44120.0,2.2,15493.0,1124.3,Q1,2018
70,20687.278,20958.320,3.8,62.8,13988.8,-49931.0,-5.2,15714.6,1193.3,Q2,2018
71,20819.269,21094.695,3.8,62.9,14102.9,-52355.0,1.2,15945.8,1306.5,Q3,2018

In [9]:
# Sort the DataFrame by the 'YearQuarter' column
econ_cleaned['YearQuarter'] = econ_cleaned['year'].astype(str) + econ_cleaned['quarter']
econ_cleaned = econ_cleaned.sort_values(by='YearQuarter')
econ_cleaned.drop(['YearQuarter'], axis=1, inplace=True)

In [10]:
quarter_to_months = {
    'Q1': ['01', '02', '03'],
    'Q2': ['04', '05', '06'],
    'Q3': ['07', '08', '09'],
    'Q4': ['10', '11', '12']
}

dates = []
for i, row in econ_cleaned.iterrows():
    for mnth in quarter_to_months[row['quarter']]:
        dates.append( str(row['year']) + '-' + mnth + '-01' )

In [11]:
# There will be a row for each month in the quarter so we have to duplicate
econ_cleaned = pd.concat([econ_cleaned] * 3, ignore_index=True)

In [12]:
# Sort the DataFrame by the 'YearQuarter' column
econ_cleaned['YearQuarter'] = econ_cleaned['year'].astype(str) + econ_cleaned['quarter']
econ_cleaned = econ_cleaned.sort_values(by='YearQuarter')
econ_cleaned.drop(['YearQuarter'], axis=1, inplace=True)

In [13]:
econ_cleaned['date'] = dates
econ_cleaned

,GDP,GNP,Unemployment Rate,Labor Force Participation Rate,Personal Consumption Expenditures,Trade Balance,Real Export,Personal Income,Personal Saving,quarter,year,date
0,18193.707,18405.862,5.4,62.8,12224.7,-40254.0,1.1,13696.9,1027.7,Q1,2015,2015-01-01
16,18193.707,18405.862,5.4,62.8,12224.7,-40254.0,1.1,13696.9,1027.7,Q1,2015,2015-02-01
32,18193.707,18405.862,5.4,62.8,12224.7,-40254.0,1.1,13696.9,1027.7,Q1,2015,2015-03-01
1,18306.960,18520.403,5.1,62.5,12347.7,-42062.0,-3.3,13809.6,1009.9,Q2,2015,2015-04-01
17,18306.960,18520.403,5.1,62.5,12347.7,-42062.0,-3.3,13809.6,1009.9,Q2,2015,2015-05-01
33,18306.960,18520.403,5.1,62.5,12347.7,-42062.0,-3.3,13809.6,1009.9,Q2,2015,2015-06-01
2,18332.079,18565.145,5.0,62.6,12397.5,-40776.0,-0.6,13881.5,1027.0,Q3,2015,2015-07-01
18,18332.079,18565.145,5.0,62.6,12397.5,-40776.0,-0.6,13881.5,1027.0,Q3,2015,2015-08-01
34,18332.079,18565.145,5.0,62.6,12397.5,-40776.0,-0.6,13881.5,1027.0,Q3,2015,2015-09-01
3,17991.348,18214.218,5.5,62.7,12083.9,-40500.0,-3.2,13593.1,1074.9,Q4,2015,2015-10-01
19,17991.348,18214.218,5.5,62.7,12083.9,-40500.0,-3.2,13593.1,1074.9,Q4,2015,2015-11-01
35,17991.348,18214.218,5.5,62.7,12083.9,-40500.0,-3.2,13593.1,1074.9,Q4,2015,2015-12-01
36,18611.617,18827.942,4.9,62.8,12637.4,-39600.0,3.1,14058.7,969.6,Q1,2016,2016-01-01
4,18611.617,18827.942,4.9,62.8,12637.4,-39600.0,3.1,14058.7,969.6,Q1,2016,2016-02-01
20,18611.617,18827.942,4.9,62.8,12637.4,-39600.0,3.1,14058.7,969.6,Q1,2016,2016-03-01
37,18775.459,18995.777,4.9,62.9,12759.1,-39027.0,6.4,14179.6,961.2,Q2,2016,2016-04-01
5,18775.459,18995.777,4.9,62.9,12759.1,-39027.0,6.4,14179.6,961.2,Q2,2016,2016-05-01
21,18775.459,18995.777,4.9,62.9,12759.1,-39027.0,6.4,14179.6,961.2,Q2,2016,2016-06-01
38,18968.041,19243.922,4.8,62.7,12881.5,-41142.0,-2.8,14322.3,974.3,Q3,2016,2016-07-01
22,18968.041,19243.922,4.8,62.7,12881.5,-41142.0,-2.8,14322.3,974.3,Q3,2016,2016-08-01
6,18968.041,19243.922,4.8,62.7,12881.5,-41142.0,-2.8,14322.3,974.3,Q3,2016,2016-09-01
39,18425.306,18640.558,4.9,62.8,12495.1,-40050.0,-1.2,13994.0,1046.2,Q4,2016,2016-10-01
23,18425.306,18640.558,4.9,62.8,12495.1,-40050.0,-1.2,13994.0,1046.2,Q4,2016,2016-11-01
7,18425.306,18640.558,4.9,62.8,12495.1,-40050.0,-1.2,13994.0,1046.2,Q4,2016,2016-12-01
24,19304.506,19568.667,4.4,62.9,13134.0,-43597.0,1.3,14728.6,1114.0,Q1,2017,2017-01-01
8,19304.506,19568.667,4.4,62.9,13134.0,-43597.0,1.3,14728.6,1114.0,Q1,2017,2017-02-01
40,19304.506,19568.667,4.4,62.9,13134.0,-43597.0,1.3,14728.6,1114.0,Q1,2017,2017-03-01
41,19561.896,19870.351,4.3,63.0,13260.3,-42279.0,2.4,14866.6,1119.0,Q2,2017,2017-04-01
25,19561.896,19870.351,4.3,63.0,13260.3,-42279.0,2.4,14866.6,1119.0,Q2,2017,2017-05-01
9,19561.896,19870.351,4.3,63.0,13260.3,-42279.0,2.4,14866.6,1119.0,Q2,2017,2017-06-01
26,19894.750,20221.660,4.2,62.7,13490.7,-44949.0,10.8,15021.9,1031.7,Q3,2017,2017-07-01
10,19894.750,20221.660,4.2,62.7,13490.7,-44949.0,10.8,15021.9,1031.7,Q3,2017,2017-08-01
42,19894.750,20221.660,4.2,62.7,13490.7,-44949.0,10.8,15021.9,1031.7,Q3,2017,2017-09-01
11,19148.194,19420.467,4.6,62.9,13049.4,-41488.0,10.8,14547.9,1030.4,Q4,2017,2017-10-01
27,19148.194,19420.467,4.6,62.9,13049.4,-41488.0,10.8,14547.9,1030.4,Q4,2017,2017-11-01
43,19148.194,19420.467,4.6,62.9,13049.4,-41488.0,10.8,14547.9,1030.4,Q4,2017,2017-12-01
12,20470.197,20772.518,3.9,62.9,13850.8,-44120.0,2.2,15493.0,1124.3,Q1,2018,2018-01-01
44,20470.197,20772.518,3.9,62.9,13850.8,-44120.0,2.2,15493.0,1124.3,Q1,2018,2018-02-01
28,20470.197,20772.518,3.9,62.9,13850.8,-44120.0,2.2,15493.0,1124.3,Q1,2018,2018-03-01
45,20687.278,20958.320,3.8,62.8,13988.8,-49931.0,-5.2,15714.6,1193.3,Q2,2018,2018-04-01
29,20687.278,20958.320,3.8,62.8,13988.8,-49931.0,-5.2,15714.6,1193.3,Q2,2018,2018-05-01
13,20687.278,20958.320,3.8,62.8,13988.8,-49931.0,-5.2,15714.6,1193.3,Q2,2018,2018-06-01
46,20819.269,21094.695,3.8,62.9,14102.9,-52355.0,1.2,15945.8,1306.5,Q3,2018,2018-07-01
14,20819.269,21094.695,3.8,62.9,14102.9,-52355.0,1.2,15945.8,1306.5,Q3,2018,2018-08-01
30,20819.269,21094.695,3.8,62.9,14102.9,-52355.0,1.2,15945.8,1306.5,Q3,2018,2018-09-01
31,20155.486,20467.925,4.0,62.9,13677.4,-46458.0,2.6,15282.2,1097.1,Q4,2018,2018-10-01
15,20155.486,20467.925,4.0,62.9,13677.4,-46458.0,2.6,15282.2,1097.1,Q4,2018,2018-11-01
47,20155.486,20467.925,4.0,62.9,13677.4,-46458.0,2.6,15282.2,1097.1,Q4,2018,2018-12-01

In [14]:
econ_cleaned.to_csv('./macroCleaned.csv')